// UI + learning copy for the six supported languages (§10). Numbers never live here — they come from nasa-data / mission-sim.
const en = {
  ui: {
    flow: { start: "Start mission", planet: "Choose a world", mission: "Choose a mission", routePick: "Choose a route", routePreview: "Preview route", objectives: "Mission objectives", budget: "Mission budget", fuel: "Fuel plan", power: "Power plan", comms: "Communications", instruments: "Science instruments", overview: "Mission overview", craft: "Choose spacecraft", build: "Modify spacecraft", next: "Next", back: "Back", learn: "Learn why", continue: "Continue", selected: "Selected", surface: "Explore the surface", orbit: "Study the orbit", survey: "Survey from a distance", limited: "Limited", balanced: "Balanced", expanded: "Expanded", explorer: "Explorer", surveyor: "Surveyor", guardian: "Guardian", review: "Review choices", confirmRoute: "Confirm route", changeRoute: "Change route", design: "Design spacecraft", score: "Engineering score", launchRisk: "Launch anyway", nasa: "NASA source", gameEstimate: "Game estimate", flight: "Flight view", control: "Mission control", cockpit: "Cockpit" },
    game: { home: "Home", missions: "Missions", brief: "Brief", route: "Route", hangar: "Hangar", launch: "Launch check", options: "Options", graphics: "Graphics", choose: "Choose your destination", chooseHint: "Choose a world to explore.", destination: "Destination", gravity: "Gravity", year: "Year", distance: "Distance from Sun", explore: "Explore mission", plot: "Plot the trajectory", dragMap: "Drag to inspect the orbital map", flightPlan: "Flight plan", transit: "Transit", required: "Required", routeHint: "Compare routes on the orbital map (positions from JPL Horizons where available).", toHangar: "Enter hangar", assemble: "Assemble your craft", dragCraft: "Drag to rotate spacecraft", engine: "Engine", fuel: "Fuel", power: "Power", comms: "Communications", science: "Science", engineCount: "Engines", tanks: "Fuel tanks", fuelLoad: "Fuel load", solar: "Solar wings", rtg: "RTG units", battery: "Battery bank", antennas: "Antennas", shield: "Debris shield", installed: "Installed instruments", mass: "Launch mass", readiness: "Readiness", toCheck: "Run launch check" },
    nav: { home: "Home", missions: "Missions", learn: "Learn", archive: "Archive" },
    home: { eyebrow: "BECOME THE", title1: "Mission", title2: "Commander", sub: "Design the mission. Command the journey. Learn from every decision.", continue: "Continue Mission", current: "CURRENT MISSION", notStarted: "Not started", attempt: "Attempt {{n}} · In progress", newMission: "New Mission", archive: "Mission Archive", tagline: "SMALL DECISIONS. BIG JOURNEYS." },
    learn: { title: "Science Lab", mentorTitle: "Mission Science Mentor", mentorGreeting: "Welcome to the Science Lab, Commander! Master the core physics of space exploration before your journey.", pick: "Pick a concept. Each one takes about two minutes.", close: "Close", back: "All concepts", next: "Next step", prev: "Previous", step: "Step {{n}} of 7", check: "Check answer", correct: "Correct!", wrong: "Not quite — try again.", source: "Source", result: "Result" },
    steps: ["Simple idea", "See it", "Try the numbers", "Real science", "Formula", "Try it", "Where this comes from"],
    voice: { play: "Play", pause: "Pause", resume: "Resume", replay: "Replay", mute: "Mute", unmute: "Unmute", captionsOn: "Captions on", captionsOff: "Captions off", language: "Language", unsupported: "Voice is not available on this device. Captions are shown instead.", noVoice: "No voice installed for this language on this device. Captions are shown instead.", speaking: "Speaking", paused: "Paused" },
    ayesha: { name: "Dr. Ayesha", role: "Mission scientist", dismiss: "Got it", listen: "Listen" },
    brief: { kicker: "MISSION BRIEF", objective: "Objective", target: "Target facts", diameter: "Diameter", distance: "Distance from Sun", period: "Orbital period", gravity: "Surface gravity", signal: "Signal delay to Earth (average)", dv: "Δv needed from Earth orbit", duration: "Transit time (Hohmann)", why: "Why it matters", image: "NASA image of the target", loading: "Loading NASA image…", none: "No NASA image available", back: "Back to missions", plan: "Plan the route", source: "Sources" },
    live: { title: "TODAY'S REAL POSITIONS", loading: "Asking NASA/JPL Horizons…", distance: "Earth → {{body}} right now", delay: "One-way radio delay", srcLive: "Source: NASA/JPL Horizons ephemeris (today)", srcDemo: "Horizons unreachable — using NASA/JPL mean orbital elements" },
    dv: { title: "ROCKET EQUATION — YOUR SHIP", have: "You have", need: "Route needs", ok: "Safe: {{pct}}% margin above what the route needs.", warn: "Tight: only {{pct}}% margin. A detour could strand you.", bad: "Not enough: {{pct}}% short. This ship cannot reach the target.", fixTanks: "Add fuel tanks or fill them fuller", fixEngine: "Pick a more efficient engine (higher Isp)", fixMass: "Remove heavy parts you do not need", src: "Engine data" },
    poll: { title: "FLIGHT DIRECTOR GO / NO-GO POLL", name: { booster: "Booster", prop: "Propulsion", power: "Power", comms: "Communications", shield: "Shielding", science: "Science", weather: "Space weather" }, go: "GO", hold: "HOLD", nogo: "NO-GO", booster: "{{pct}}% of SLS lift limit", prop: "Δv margin {{pct}}%", power: "{{gen}} kW made, {{draw}} kW used", comms: "{{n}} antenna(s)", shield: "Route hazard {{pct}}%", science: "Science value {{n}}", loading: "Checking NASA solar flares…", weather: "Latest flare class {{cls}}", quiet: "Sun quiet — no flares in 14 days", blocked: "NO-GO: fix the red items in the Builder before launch.", accept: "I accept {{n}} HOLD item(s) and take the risk", allgo: "All stations GO. You are cleared for launch." },
  },
  concepts: {
    rocket: { title: "Rocket equation & Δv", simple: "A rocket throws fuel out the back so it moves forward. Faster exhaust and more fuel give a bigger change in speed, called delta-v (Δv).", demo: "Watch the exhaust: each puff of gas pushes the rocket the opposite way.", interactive: "Move the sliders. See how engine efficiency (Isp) and the full-to-empty mass ratio change Δv.", isp: "Engine efficiency (Isp)", ratio: "Full ÷ empty mass", science: "Konstantin Tsiolkovsky showed that Δv depends only on exhaust speed and the mass ratio. Because of the logarithm, adding more fuel helps less and less.", formulaNote: "Isp = specific impulse (s), g₀ = 9.80665 m/s², m₀ = full mass, m_f = empty mass.", q: "Which gives a rocket more Δv?", a: ["Doubling the fuel", "Doubling exhaust speed", "They are always equal"], correct: 1, explain: "Δv grows in step with exhaust speed, but only with the logarithm of the mass ratio.", ayesha: "Every mission starts with one question: do we have enough delta-v? Let's find out together." },
    orbit: { title: "Orbits & travel time", simple: "Planets farther from the Sun move slower and take longer to go around it. That sets how long trips take.", demo: "Inner planets race around; outer planets crawl.", interactive: "Drag the distance. See how long one orbit takes.", dist: "Distance from the Sun (AU)", science: "Johannes Kepler found that the square of a planet's orbital period equals the cube of its distance, when measured in years and astronomical units.", formulaNote: "T = orbital period in Earth years, a = average distance in AU.", q: "Mars is about 1.52 AU from the Sun. Roughly how long is its year?", a: ["About 1 Earth year", "About 1.9 Earth years", "About 5 Earth years"], correct: 1, explain: "1.52³ ≈ 3.5, and √3.5 ≈ 1.88 years — matching NASA's 687 days.", ayesha: "Timing is everything. Planets move while we travel, so we aim where they will be." },
    light: { title: "Sunlight & signal delay", simple: "Far from the Sun, solar panels get much less light. Radio messages also take longer to travel home.", demo: "Sunlight spreads out like a growing ball, so it gets weaker with distance.", interactive: "Pick a destination. See solar power and radio delay.", body: "Destination", power: "Solar power vs Earth", delay: "One-way radio delay", science: "Light spreads over a sphere, so its strength falls with the square of distance. Radio signals travel at the speed of light, about 299,792 km per second.", formulaNote: "P = power, d = distance in AU, c = speed of light.", q: "At Jupiter (5.2 AU), how much sunlight do solar panels get compared to Earth?", a: ["About 50%", "About 20%", "About 4%"], correct: 2, explain: "1 ÷ 5.2² ≈ 0.037, about 4% — that's why Juno needs huge solar arrays.", ayesha: "Far from the Sun, power and patience both become precious. Plan for both." },
  },
  ayeshaTips: { build: "Check your delta-v before anything else. If it's below what the route needs, add fuel or a more efficient engine.", launch: "Launch is the hardest part. Most of your fuel is spent just escaping Earth's gravity." },
};

type Tree = typeof en;

const bn: Tree = {
  ui: {
    flow: { start: "মিশন শুরু", planet: "গ্রহ বেছে নিন", mission: "মিশন বেছে নিন", routePick: "পথ বেছে নিন", routePreview: "পথ দেখুন", objectives: "মিশনের লক্ষ্য", budget: "মিশনের বাজেট", fuel: "জ্বালানির পরিকল্পনা", power: "বিদ্যুতের পরিকল্পনা", comms: "যোগাযোগ", instruments: "বৈজ্ঞানিক যন্ত্র", overview: "মিশন পর্যালোচনা", craft: "যান বেছে নিন", build: "যান পরিবর্তন", next: "পরবর্তী", back: "পেছনে", learn: "কেন শিখুন", continue: "এগিয়ে যান", selected: "নির্বাচিত", surface: "পৃষ্ঠে অনুসন্ধান", orbit: "কক্ষপথ পরীক্ষা", survey: "দূর থেকে জরিপ", limited: "সীমিত", balanced: "মাঝারি", expanded: "বর্ধিত", explorer: "অভিযাত্রী", surveyor: "জরিপকারী", guardian: "রক্ষক", review: "সিদ্ধান্ত দেখুন", confirmRoute: "পথ নিশ্চিত করুন", changeRoute: "পথ বদলান", design: "যান তৈরি করুন", score: "প্রকৌশল স্কোর", launchRisk: "ঝুঁকি নিয়ে লঞ্চ", nasa: "NASA উৎস", gameEstimate: "গেমের অনুমান", flight: "উড়ান দৃশ্য", control: "মিশন নিয়ন্ত্রণ", cockpit: "ককপিট" },
    game: { home: "হোম", missions: "মিশন", brief: "মিশন পরিচিতি", route: "পথ", hangar: "হ্যাঙ্গার", launch: "লঞ্চ পরীক্ষা", options: "বিকল্প", graphics: "গ্রাফিক্স", choose: "গন্তব্য বেছে নিন", chooseHint: "যে বিশ্বটি ঘুরে দেখতে চান বেছে নিন।", destination: "গন্তব্য", gravity: "মাধ্যাকর্ষণ", year: "বছর", distance: "সূর্য থেকে দূরত্ব", explore: "মিশন দেখুন", plot: "পথ নির্ধারণ করুন", dragMap: "কক্ষপথ দেখতে টানুন", flightPlan: "উড়ানের পরিকল্পনা", transit: "যাত্রা", required: "প্রয়োজন", routeHint: "NASA/JPL-এর কক্ষপথ দেখে পথ তুলনা করুন।", toHangar: "হ্যাঙ্গারে যান", assemble: "মহাকাশযান তৈরি করুন", dragCraft: "যান ঘোরাতে টানুন", engine: "ইঞ্জিন", fuel: "জ্বালানি", power: "বিদ্যুৎ", comms: "যোগাযোগ", science: "বিজ্ঞান", engineCount: "ইঞ্জিন সংখ্যা", tanks: "জ্বালানি ট্যাঙ্ক", fuelLoad: "জ্বালানির পরিমাণ", solar: "সৌর পাখা", rtg: "RTG ইউনিট", battery: "ব্যাটারি", antennas: "অ্যান্টেনা", shield: "সুরক্ষা ঢাল", installed: "বসানো যন্ত্র", mass: "উৎক্ষেপণ ভর", readiness: "প্রস্তুতি", toCheck: "লঞ্চ পরীক্ষা করুন" },
    nav: { home: "হোম", missions: "মিশন", learn: "শিখুন", archive: "আর্কাইভ" },
    home: { eyebrow: "হয়ে উঠুন", title1: "মিশন", title2: "কমান্ডার", sub: "মিশন ডিজাইন করুন। যাত্রা পরিচালনা করুন। প্রতিটি সিদ্ধান্ত থেকে শিখুন।", continue: "মিশন চালিয়ে যান", current: "বর্তমান মিশন", notStarted: "শুরু হয়নি", attempt: "চেষ্টা {{n}} · চলছে", newMission: "নতুন মিশন", archive: "মিশন আর্কাইভ", tagline: "ছোট সিদ্ধান্ত। বড় যাত্রা।" },
    learn: { title: "বিজ্ঞান ল্যাব", mentorTitle: "মিশন বিজ্ঞান মেন্টর", mentorGreeting: "বিজ্ঞান ল্যাবে স্বাগতম, কমান্ডার! যাত্রার আগে মহাকাশ অভিযানের মূল পদার্থবিজ্ঞান জেনে নিন।", pick: "একটি বিষয় বেছে নিন। প্রতিটিতে প্রায় দুই মিনিট লাগে।", close: "বন্ধ", back: "সব বিষয়", next: "পরের ধাপ", prev: "আগের", step: "ধাপ {{n}} / ৭", check: "উত্তর যাচাই", correct: "সঠিক!", wrong: "হয়নি — আবার চেষ্টা করুন।", source: "উৎস", result: "ফলাফল" },
    steps: ["সহজ ধারণা", "দেখুন", "সংখ্যা নিয়ে খেলুন", "আসল বিজ্ঞান", "সূত্র", "চেষ্টা করুন", "তথ্যের উৎস"],
    voice: { play: "চালান", pause: "থামান", resume: "আবার চালান", replay: "আবার শুনুন", mute: "নিঃশব্দ", unmute: "শব্দ চালু", captionsOn: "ক্যাপশন চালু", captionsOff: "ক্যাপশন বন্ধ", language: "ভাষা", unsupported: "এই ডিভাইসে ভয়েস নেই। ক্যাপশন দেখানো হচ্ছে।", noVoice: "এই ডিভাইসে এই ভাষার ভয়েস ইনস্টল নেই। ক্যাপশন দেখানো হচ্ছে।", speaking: "বলছে", paused: "থামানো" },
    ayesha: { name: "ড. আয়েশা", role: "মিশন বিজ্ঞানী", dismiss: "বুঝেছি", listen: "শুনুন" },
    brief: { kicker: "মিশন ব্রিফ", objective: "লক্ষ্য", target: "গন্তব্যের তথ্য", diameter: "ব্যাস", distance: "সূর্য থেকে দূরত্ব", period: "কক্ষপথের সময়", gravity: "পৃষ্ঠের মাধ্যাকর্ষণ", signal: "পৃথিবীতে সংকেতের দেরি (গড়)", dv: "পৃথিবীর কক্ষপথ থেকে প্রয়োজনীয় Δv", duration: "যাত্রার সময় (হোমান)", why: "কেন গুরুত্বপূর্ণ", image: "গন্তব্যের NASA ছবি", loading: "NASA ছবি লোড হচ্ছে…", none: "NASA ছবি পাওয়া যায়নি", back: "মিশনে ফিরুন", plan: "পথ পরিকল্পনা করুন", source: "উৎস" },
    live: { title: "আজকের প্রকৃত অবস্থান", loading: "NASA/JPL Horizons-এ জিজ্ঞাসা করা হচ্ছে…", distance: "এখন পৃথিবী → {{body}}", delay: "একমুখী রেডিও দেরি", srcLive: "উৎস: NASA/JPL Horizons (আজ)", srcDemo: "Horizons পাওয়া যায়নি — NASA/JPL গড় কক্ষপথ উপাদান ব্যবহৃত" },
    dv: { title: "রকেট সমীকরণ — আপনার যান", have: "আপনার আছে", need: "পথে লাগবে", ok: "নিরাপদ: প্রয়োজনের চেয়ে {{pct}}% বেশি।", warn: "টানাটানি: মাত্র {{pct}}% বাড়তি। ঘুরপথে আটকে যেতে পারেন।", bad: "যথেষ্ট নয়: {{pct}}% কম। এই যান গন্তব্যে পৌঁছাতে পারবে না।", fixTanks: "আরও জ্বালানি ট্যাঙ্ক যোগ করুন বা পূর্ণ করুন", fixEngine: "আরও দক্ষ ইঞ্জিন বেছে নিন (বেশি Isp)", fixMass: "অপ্রয়োজনীয় ভারী অংশ সরান", src: "ইঞ্জিনের তথ্য" },
    poll: { title: "ফ্লাইট ডিরেক্টর GO / NO-GO পোল", name: { booster: "বুস্টার", prop: "প্রপালশন", power: "বিদ্যুৎ", comms: "যোগাযোগ", shield: "সুরক্ষা ঢাল", science: "বিজ্ঞান", weather: "মহাকাশ আবহাওয়া" }, go: "GO", hold: "HOLD", nogo: "NO-GO", booster: "SLS সীমার {{pct}}%", prop: "Δv মার্জিন {{pct}}%", power: "{{gen}} kW উৎপাদন, {{draw}} kW ব্যবহার", comms: "{{n}}টি অ্যান্টেনা", shield: "পথের ঝুঁকি {{pct}}%", science: "বিজ্ঞান মান {{n}}", loading: "NASA সৌরঝড় যাচাই হচ্ছে…", weather: "সর্বশেষ ফ্লেয়ার শ্রেণি {{cls}}", quiet: "সূর্য শান্ত — ১৪ দিনে ফ্লেয়ার নেই", blocked: "NO-GO: উৎক্ষেপণের আগে বিল্ডারে লাল বিষয়গুলো ঠিক করুন।", accept: "আমি {{n}}টি HOLD মেনে ঝুঁকি নিচ্ছি", allgo: "সব স্টেশন GO। উৎক্ষেপণের অনুমতি দেওয়া হলো।" },
  },
  concepts: {
    rocket: { title: "রকেট সমীকরণ ও Δv", simple: "রকেট পেছনে জ্বালানি ছুড়ে সামনে এগোয়। দ্রুত নিঃসরণ ও বেশি জ্বালানি মানে গতির বড় পরিবর্তন, যাকে ডেল্টা-ভি (Δv) বলে।", demo: "নিঃসরণ দেখুন: প্রতিটি গ্যাসের ধাক্কা রকেটকে উল্টো দিকে ঠেলে।", interactive: "স্লাইডার সরান। ইঞ্জিনের দক্ষতা (Isp) ও ভর অনুপাত কীভাবে Δv বদলায় দেখুন।", isp: "ইঞ্জিনের দক্ষতা (Isp)", ratio: "পূর্ণ ÷ খালি ভর", science: "কনস্তানতিন সিওলকোভস্কি দেখিয়েছেন Δv কেবল নিঃসরণ গতি ও ভর অনুপাতের ওপর নির্ভর করে। লগারিদমের কারণে বেশি জ্বালানি যোগ করলে লাভ ক্রমশ কমে।", formulaNote: "Isp = নির্দিষ্ট আবেগ (সেকেন্ড), g₀ = 9.80665 m/s², m₀ = পূর্ণ ভর, m_f = খালি ভর।", q: "কোনটি রকেটকে বেশি Δv দেয়?", a: ["জ্বালানি দ্বিগুণ করা", "নিঃসরণ গতি দ্বিগুণ করা", "দুটো সবসময় সমান"], correct: 1, explain: "Δv নিঃসরণ গতির সাথে সমানুপাতে বাড়ে, কিন্তু ভর অনুপাতের কেবল লগারিদমের সাথে।", ayesha: "প্রতিটি মিশন একটি প্রশ্ন দিয়ে শুরু হয়: আমাদের কি যথেষ্ট ডেল্টা-ভি আছে? চলুন একসাথে খুঁজে দেখি।" },
    orbit: { title: "কক্ষপথ ও ভ্রমণের সময়", simple: "সূর্য থেকে দূরের গ্রহগুলো ধীরে চলে এবং একবার ঘুরতে বেশি সময় নেয়। এতে যাত্রার সময় নির্ধারিত হয়।", demo: "ভেতরের গ্রহ দ্রুত ঘোরে; বাইরের গ্রহ ধীরে।", interactive: "দূরত্ব টানুন। একটি কক্ষপথে কত সময় লাগে দেখুন।", dist: "সূর্য থেকে দূরত্ব (AU)", science: "ইয়োহানেস কেপলার দেখেছেন, বছর ও জ্যোতির্বিদ্যা একক দিয়ে মাপলে কক্ষপথ সময়ের বর্গ দূরত্বের ঘনের সমান।", formulaNote: "T = পৃথিবী-বছরে কক্ষপথ সময়, a = AU-তে গড় দূরত্ব।", q: "মঙ্গল সূর্য থেকে প্রায় 1.52 AU দূরে। তার বছর প্রায় কত?", a: ["প্রায় ১ পৃথিবী-বছর", "প্রায় ১.৯ পৃথিবী-বছর", "প্রায় ৫ পৃথিবী-বছর"], correct: 1, explain: "1.52³ ≈ 3.5, আর √3.5 ≈ 1.88 বছর — NASA-র 687 দিনের সাথে মেলে।", ayesha: "সময়ই সব। আমরা যাত্রা করার সময় গ্রহও সরে, তাই আমরা লক্ষ্য করি গ্রহটি যেখানে থাকবে।" },
    light: { title: "সূর্যালোক ও সংকেত বিলম্ব", simple: "সূর্য থেকে দূরে সোলার প্যানেল অনেক কম আলো পায়। রেডিও বার্তাও বাড়ি পৌঁছাতে বেশি সময় নেয়।", demo: "সূর্যালোক বড় হতে থাকা গোলকের মতো ছড়ায়, তাই দূরত্বে দুর্বল হয়।", interactive: "একটি গন্তব্য বেছে নিন। সৌরশক্তি ও রেডিও বিলম্ব দেখুন।", body: "গন্তব্য", power: "পৃথিবীর তুলনায় সৌরশক্তি", delay: "একমুখী রেডিও বিলম্ব", science: "আলো একটি গোলকে ছড়ায়, তাই তার শক্তি দূরত্বের বর্গ হারে কমে। রেডিও সংকেত আলোর গতিতে চলে, সেকেন্ডে প্রায় ২,৯৯,৭৯২ কিমি।", formulaNote: "P = শক্তি, d = AU-তে দূরত্ব, c = আলোর গতি।", q: "বৃহস্পতিতে (5.2 AU) পৃথিবীর তুলনায় সোলার প্যানেল কতটা সূর্যালোক পায়?", a: ["প্রায় ৫০%", "প্রায় ২০%", "প্রায় ৪%"], correct: 2, explain: "1 ÷ 5.2² ≈ 0.037, প্রায় ৪% — তাই জুনোর বিশাল সোলার প্যানেল দরকার।", ayesha: "সূর্য থেকে দূরে শক্তি ও ধৈর্য দুটোই মূল্যবান। দুটোর জন্যই পরিকল্পনা করুন।" },
  },
  ayeshaTips: { build: "সবার আগে ডেল্টা-ভি যাচাই করুন। রুটের প্রয়োজনের চেয়ে কম হলে জ্বালানি বা আরও দক্ষ ইঞ্জিন যোগ করুন।", launch: "উৎক্ষেপণই সবচেয়ে কঠিন অংশ। বেশিরভাগ জ্বালানি খরচ হয় শুধু পৃথিবীর মাধ্যাকর্ষণ ছাড়াতে।" },
};

const hi: Tree = {
  ui: {
    flow: { start: "मिशन शुरू", planet: "दुनिया चुनें", mission: "मिशन चुनें", routePick: "मार्ग चुनें", routePreview: "मार्ग देखें", objectives: "मिशन लक्ष्य", budget: "मिशन बजट", fuel: "ईंधन योजना", power: "ऊर्जा योजना", comms: "संचार", instruments: "वैज्ञानिक उपकरण", overview: "मिशन सारांश", craft: "यान चुनें", build: "यान बदलें", next: "आगे", back: "पीछे", learn: "क्यों जानें", continue: "जारी रखें", selected: "चुना गया", surface: "सतह की खोज", orbit: "कक्षा का अध्ययन", survey: "दूर से सर्वेक्षण", limited: "सीमित", balanced: "संतुलित", expanded: "विस्तृत", explorer: "एक्सप्लोरर", surveyor: "सर्वेयर", guardian: "गार्डियन", review: "चुनाव देखें", confirmRoute: "मार्ग पक्का करें", changeRoute: "मार्ग बदलें", design: "यान बनाएँ", score: "इंजीनियरिंग स्कोर", launchRisk: "जोखिम लेकर लॉन्च", nasa: "NASA स्रोत", gameEstimate: "खेल अनुमान", flight: "उड़ान दृश्य", control: "मिशन कंट्रोल", cockpit: "कॉकपिट" },
    game: { home: "घर", missions: "मिशन", brief: "मिशन परिचय", route: "मार्ग", hangar: "हैंगर", launch: "लॉन्च जांच", options: "विकल्प", graphics: "ग्राफ़िक्स", choose: "गंतव्य चुनें", chooseHint: "खोजने के लिए एक दुनिया चुनें।", destination: "गंतव्य", gravity: "गुरुत्व", year: "वर्ष", distance: "सूर्य से दूरी", explore: "मिशन देखें", plot: "रास्ता बनाएँ", dragMap: "कक्षा देखने के लिए खींचें", flightPlan: "उड़ान योजना", transit: "यात्रा", required: "आवश्यक", routeHint: "NASA/JPL की कक्षाओं से रास्ते तुलना करें।", toHangar: "हैंगर में जाएँ", assemble: "अपना यान बनाएँ", dragCraft: "यान घुमाने के लिए खींचें", engine: "इंजन", fuel: "ईंधन", power: "ऊर्जा", comms: "संचार", science: "विज्ञान", engineCount: "इंजन संख्या", tanks: "ईंधन टैंक", fuelLoad: "ईंधन मात्रा", solar: "सौर पंख", rtg: "RTG इकाई", battery: "बैटरी", antennas: "एंटेना", shield: "सुरक्षा ढाल", installed: "लगे उपकरण", mass: "प्रक्षेपण भार", readiness: "तैयारी", toCheck: "लॉन्च जांचें" },
    nav: { home: "होम", missions: "मिशन", learn: "सीखें", archive: "संग्रह" },
    home: { eyebrow: "बनिए", title1: "मिशन", title2: "कमांडर", sub: "मिशन डिज़ाइन करें। यात्रा की कमान संभालें। हर फ़ैसले से सीखें।", continue: "मिशन जारी रखें", current: "वर्तमान मिशन", notStarted: "शुरू नहीं हुआ", attempt: "प्रयास {{n}} · जारी", newMission: "नया मिशन", archive: "मिशन संग्रह", tagline: "छोटे फ़ैसले। बड़ी यात्राएँ।" },
    learn: { title: "विज्ञान प्रयोगशाला", mentorTitle: "मिशन विज्ञान मेंटर", mentorGreeting: "विज्ञान प्रयोगशाला में आपका स्वागत है, कमांडर! यात्रा से पहले अंतरिक्ष भौतिकी के मूल सिद्धांतों को समझें।", pick: "एक विषय चुनें। हर एक में लगभग दो मिनट लगते हैं।", close: "बंद करें", back: "सभी विषय", next: "अगला चरण", prev: "पिछला", step: "चरण {{n}} / 7", check: "उत्तर जाँचें", correct: "सही!", wrong: "पूरी तरह नहीं — फिर कोशिश करें।", source: "स्रोत", result: "परिणाम" },
    steps: ["सरल विचार", "देखें", "संख्याएँ आज़माएँ", "असली विज्ञान", "सूत्र", "आज़माएँ", "यह कहाँ से आया"],
    voice: { play: "चलाएँ", pause: "रोकें", resume: "फिर चलाएँ", replay: "दोबारा सुनें", mute: "म्यूट", unmute: "आवाज़ चालू", captionsOn: "कैप्शन चालू", captionsOff: "कैप्शन बंद", language: "भाषा", unsupported: "इस डिवाइस पर आवाज़ उपलब्ध नहीं है। कैप्शन दिखाए जा रहे हैं।", noVoice: "इस डिवाइस पर इस भाषा की आवाज़ इंस्टॉल नहीं है। कैप्शन दिखाए जा रहे हैं।", speaking: "बोल रही हैं", paused: "रुका हुआ" },
    ayesha: { name: "डॉ. आयशा", role: "मिशन वैज्ञानिक", dismiss: "समझ गया", listen: "सुनें" },
    brief: { kicker: "मिशन ब्रीफ़", objective: "उद्देश्य", target: "लक्ष्य के तथ्य", diameter: "व्यास", distance: "सूर्य से दूरी", period: "कक्षीय अवधि", gravity: "सतह गुरुत्व", signal: "पृथ्वी तक संकेत देरी (औसत)", dv: "पृथ्वी कक्षा से आवश्यक Δv", duration: "यात्रा समय (होमन)", why: "यह क्यों मायने रखता है", image: "लक्ष्य की NASA तस्वीर", loading: "NASA तस्वीर लोड हो रही है…", none: "कोई NASA तस्वीर उपलब्ध नहीं", back: "मिशन पर वापस", plan: "मार्ग की योजना बनाएँ", source: "स्रोत" },
    live: { title: "आज की वास्तविक स्थिति", loading: "NASA/JPL Horizons से पूछ रहे हैं…", distance: "अभी पृथ्वी → {{body}}", delay: "एकतरफ़ा रेडियो देरी", srcLive: "स्रोत: NASA/JPL Horizons (आज)", srcDemo: "Horizons उपलब्ध नहीं — NASA/JPL औसत कक्षीय तत्व" },
    dv: { title: "रॉकेट समीकरण — आपका यान", have: "आपके पास", need: "मार्ग को चाहिए", ok: "सुरक्षित: ज़रूरत से {{pct}}% अधिक।", warn: "कम: केवल {{pct}}% अतिरिक्त। चक्कर में फँस सकते हैं।", bad: "पर्याप्त नहीं: {{pct}}% कम। यह यान लक्ष्य तक नहीं पहुँच सकता।", fixTanks: "ईंधन टैंक जोड़ें या भरें", fixEngine: "अधिक कुशल इंजन चुनें (ऊँचा Isp)", fixMass: "अनावश्यक भारी हिस्से हटाएँ", src: "इंजन डेटा" },
    poll: { title: "फ़्लाइट डायरेक्टर GO / NO-GO पोल", name: { booster: "बूस्टर", prop: "प्रणोदन", power: "बिजली", comms: "संचार", shield: "कवच", science: "विज्ञान", weather: "अंतरिक्ष मौसम" }, go: "GO", hold: "HOLD", nogo: "NO-GO", booster: "SLS सीमा का {{pct}}%", prop: "Δv मार्जिन {{pct}}%", power: "{{gen}} kW बना, {{draw}} kW खर्च", comms: "{{n}} एंटीना", shield: "मार्ग जोखिम {{pct}}%", science: "विज्ञान मूल्य {{n}}", loading: "NASA सौर ज्वालाएँ जाँची जा रही हैं…", weather: "नवीनतम ज्वाला वर्ग {{cls}}", quiet: "सूर्य शांत — 14 दिनों में कोई ज्वाला नहीं", blocked: "NO-GO: लॉन्च से पहले बिल्डर में लाल चीज़ें ठीक करें।", accept: "मैं {{n}} HOLD स्वीकार कर जोखिम लेता हूँ", allgo: "सभी स्टेशन GO। लॉन्च की अनुमति है।" },
  },
  concepts: {
    rocket: { title: "रॉकेट समीकरण और Δv", simple: "रॉकेट ईंधन को पीछे फेंककर आगे बढ़ता है। तेज़ निकास और ज़्यादा ईंधन से गति में बड़ा बदलाव होता है, जिसे डेल्टा-वी (Δv) कहते हैं।", demo: "निकास देखें: गैस का हर झोंका रॉकेट को उलटी दिशा में धकेलता है।", interactive: "स्लाइडर हिलाएँ। देखें इंजन दक्षता (Isp) और द्रव्यमान अनुपात Δv को कैसे बदलते हैं।", isp: "इंजन दक्षता (Isp)", ratio: "भरा ÷ खाली द्रव्यमान", science: "कॉन्स्टेंटिन त्सियोल्कोव्स्की ने दिखाया कि Δv केवल निकास गति और द्रव्यमान अनुपात पर निर्भर है। लघुगणक के कारण ज़्यादा ईंधन जोड़ने का फ़ायदा घटता जाता है।", formulaNote: "Isp = विशिष्ट आवेग (सेकंड), g₀ = 9.80665 m/s², m₀ = भरा द्रव्यमान, m_f = खाली द्रव्यमान।", q: "रॉकेट को ज़्यादा Δv किससे मिलता है?", a: ["ईंधन दोगुना करने से", "निकास गति दोगुनी करने से", "दोनों हमेशा बराबर"], correct: 1, explain: "Δv निकास गति के अनुपात में बढ़ता है, पर द्रव्यमान अनुपात के केवल लघुगणक के साथ।", ayesha: "हर मिशन एक सवाल से शुरू होता है: क्या हमारे पास पर्याप्त डेल्टा-वी है? चलिए साथ मिलकर पता करें।" },
    orbit: { title: "कक्षाएँ और यात्रा का समय", simple: "सूर्य से दूर के ग्रह धीमे चलते हैं और एक चक्कर में ज़्यादा समय लेते हैं। इसी से यात्रा का समय तय होता है।", demo: "भीतरी ग्रह तेज़ी से घूमते हैं; बाहरी ग्रह धीरे।", interactive: "दूरी खींचें। देखें एक कक्षा में कितना समय लगता है।", dist: "सूर्य से दूरी (AU)", science: "योहानेस केप्लर ने पाया कि वर्षों और खगोलीय इकाइयों में मापने पर कक्षा-काल का वर्ग दूरी के घन के बराबर होता है।", formulaNote: "T = पृथ्वी-वर्षों में कक्षा-काल, a = AU में औसत दूरी।", q: "मंगल सूर्य से लगभग 1.52 AU दूर है। उसका वर्ष लगभग कितना है?", a: ["लगभग 1 पृथ्वी-वर्ष", "लगभग 1.9 पृथ्वी-वर्ष", "लगभग 5 पृथ्वी-वर्ष"], correct: 1, explain: "1.52³ ≈ 3.5, और √3.5 ≈ 1.88 वर्ष — NASA के 687 दिनों से मेल खाता है।", ayesha: "समय ही सब कुछ है। यात्रा के दौरान ग्रह चलते रहते हैं, इसलिए हम वहाँ निशाना लगाते हैं जहाँ वे होंगे।" },
    light: { title: "सूर्य का प्रकाश और सिग्नल देरी", simple: "सूर्य से दूर सोलर पैनल को बहुत कम रोशनी मिलती है। रेडियो संदेश भी घर पहुँचने में ज़्यादा समय लेते हैं।", demo: "सूर्य का प्रकाश फैलते गोले की तरह फैलता है, इसलिए दूरी के साथ कमज़ोर होता है।", interactive: "एक गंतव्य चुनें। सौर ऊर्जा और रेडियो देरी देखें।", body: "गंतव्य", power: "पृथ्वी की तुलना में सौर ऊर्जा", delay: "एकतरफ़ा रेडियो देरी", science: "प्रकाश एक गोले पर फैलता है, इसलिए उसकी शक्ति दूरी के वर्ग के साथ घटती है। रेडियो सिग्नल प्रकाश की गति से चलते हैं, लगभग 2,99,792 किमी प्रति सेकंड।", formulaNote: "P = शक्ति, d = AU में दूरी, c = प्रकाश की गति।", q: "बृहस्पति (5.2 AU) पर पृथ्वी की तुलना में सोलर पैनल को कितनी धूप मिलती है?", a: ["लगभग 50%", "लगभग 20%", "लगभग 4%"], correct: 2, explain: "1 ÷ 5.2² ≈ 0.037, लगभग 4% — इसीलिए जूनो को विशाल सोलर पैनल चाहिए।", ayesha: "सूर्य से दूर, ऊर्जा और धैर्य दोनों कीमती हो जाते हैं। दोनों की योजना बनाएँ।" },
  },
  ayeshaTips: { build: "सबसे पहले डेल्टा-वी जाँचें। अगर यह रूट की ज़रूरत से कम है, तो ईंधन या ज़्यादा कुशल इंजन जोड़ें।", launch: "प्रक्षेपण सबसे कठिन हिस्सा है। ज़्यादातर ईंधन सिर्फ़ पृथ्वी के गुरुत्वाकर्षण से निकलने में खर्च होता है।" },
};

const es: Tree = {
  ui: {
    flow: { start: "Iniciar misión", planet: "Elige un mundo", mission: "Elige una misión", routePick: "Elige la ruta", routePreview: "Vista de la ruta", objectives: "Objetivos", budget: "Presupuesto", fuel: "Plan de combustible", power: "Plan de energía", comms: "Comunicaciones", instruments: "Instrumentos científicos", overview: "Resumen de misión", craft: "Elige nave", build: "Modifica la nave", next: "Siguiente", back: "Atrás", learn: "Aprende por qué", continue: "Continuar", selected: "Seleccionado", surface: "Explorar superficie", orbit: "Estudiar órbita", survey: "Estudiar desde lejos", limited: "Limitado", balanced: "Equilibrado", expanded: "Ampliado", explorer: "Explorador", surveyor: "Topógrafo", guardian: "Guardián", review: "Revisar elecciones", confirmRoute: "Confirmar ruta", changeRoute: "Cambiar ruta", design: "Diseñar nave", score: "Puntuación técnica", launchRisk: "Lanzar con riesgo", nasa: "Fuente NASA", gameEstimate: "Estimación del juego", flight: "Vista de vuelo", control: "Control de misión", cockpit: "Cabina" },
    game: { home: "Inicio", missions: "Misiones", brief: "Informe", route: "Ruta", hangar: "Hangar", launch: "Revisión", options: "Opciones", graphics: "Gráficos", choose: "Elige tu destino", chooseHint: "Elige un mundo para explorar.", destination: "Destino", gravity: "Gravedad", year: "Año", distance: "Distancia al Sol", explore: "Explorar misión", plot: "Traza la ruta", dragMap: "Arrastra para ver la órbita", flightPlan: "Plan de vuelo", transit: "Tránsito", required: "Necesario", routeHint: "Compara rutas con las órbitas de NASA/JPL.", toHangar: "Ir al hangar", assemble: "Construye tu nave", dragCraft: "Arrastra para girar la nave", engine: "Motor", fuel: "Combustible", power: "Energía", comms: "Comunicaciones", science: "Ciencia", engineCount: "Motores", tanks: "Tanques", fuelLoad: "Carga de combustible", solar: "Paneles solares", rtg: "Unidades RTG", battery: "Batería", antennas: "Antenas", shield: "Escudo de escombros", installed: "Instrumentos instalados", mass: "Masa de lanzamiento", readiness: "Preparación", toCheck: "Revisar lanzamiento" },
    nav: { home: "Inicio", missions: "Misiones", learn: "Aprender", archive: "Archivo" },
    home: { eyebrow: "CONVIÉRTETE EN", title1: "Comandante", title2: "de Misión", sub: "Diseña la misión. Dirige el viaje. Aprende de cada decisión.", continue: "Continuar misión", current: "MISIÓN ACTUAL", notStarted: "Sin empezar", attempt: "Intento {{n}} · En curso", newMission: "Nueva misión", archive: "Archivo de misiones", tagline: "PEQUEÑAS DECISIONES. GRANDES VIAJES." },
    learn: { title: "Laboratorio de ciencia", mentorTitle: "Mentora científica de misión", mentorGreeting: "¡Te damos la bienvenida al Laboratorio de Ciencias, comandante! Domina la física espacial antes de tu viaje.", pick: "Elige un concepto. Cada uno toma unos dos minutos.", close: "Cerrar", back: "Todos los conceptos", next: "Siguiente paso", prev: "Anterior", step: "Paso {{n}} de 7", check: "Comprobar", correct: "¡Correcto!", wrong: "Casi — inténtalo otra vez.", source: "Fuente", result: "Resultado" },
    steps: ["Idea sencilla", "Míralo", "Prueba los números", "Ciencia real", "Fórmula", "Pruébalo", "De dónde viene"],
    voice: { play: "Reproducir", pause: "Pausa", resume: "Continuar", replay: "Repetir", mute: "Silenciar", unmute: "Activar sonido", captionsOn: "Subtítulos sí", captionsOff: "Subtítulos no", language: "Idioma", unsupported: "La voz no está disponible en este dispositivo. Se muestran subtítulos.", noVoice: "No hay voz instalada para este idioma en este dispositivo. Se muestran subtítulos.", speaking: "Hablando", paused: "En pausa" },
    ayesha: { name: "Dra. Ayesha", role: "Científica de misión", dismiss: "Entendido", listen: "Escuchar" },
    brief: { kicker: "INFORME DE MISIÓN", objective: "Objetivo", target: "Datos del destino", diameter: "Diámetro", distance: "Distancia al Sol", period: "Periodo orbital", gravity: "Gravedad superficial", signal: "Retraso de señal a la Tierra (media)", dv: "Δv necesario desde órbita terrestre", duration: "Tiempo de tránsito (Hohmann)", why: "Por qué importa", image: "Imagen de la NASA del destino", loading: "Cargando imagen de la NASA…", none: "No hay imagen de la NASA", back: "Volver a misiones", plan: "Planificar la ruta", source: "Fuentes" },
    live: { title: "POSICIONES REALES DE HOY", loading: "Consultando NASA/JPL Horizons…", distance: "Tierra → {{body}} ahora", delay: "Retraso de radio (ida)", srcLive: "Fuente: efemérides NASA/JPL Horizons (hoy)", srcDemo: "Horizons no disponible — elementos orbitales medios NASA/JPL" },
    dv: { title: "ECUACIÓN DEL COHETE — TU NAVE", have: "Tienes", need: "La ruta necesita", ok: "Seguro: {{pct}}% de margen sobre lo necesario.", warn: "Justo: solo {{pct}}% de margen. Un desvío podría dejarte varado.", bad: "Insuficiente: faltan {{pct}}%. Esta nave no llega al destino.", fixTanks: "Añade tanques o llénalos más", fixEngine: "Elige un motor más eficiente (mayor Isp)", fixMass: "Quita piezas pesadas que no necesites", src: "Datos del motor" },
    poll: { title: "SONDEO GO / NO-GO DEL DIRECTOR DE VUELO", name: { booster: "Cohete", prop: "Propulsión", power: "Energía", comms: "Comunicaciones", shield: "Blindaje", science: "Ciencia", weather: "Clima espacial" }, go: "GO", hold: "ESPERA", nogo: "NO-GO", booster: "{{pct}}% del límite del SLS", prop: "Margen Δv {{pct}}%", power: "{{gen}} kW generados, {{draw}} kW usados", comms: "{{n}} antena(s)", shield: "Riesgo de ruta {{pct}}%", science: "Valor científico {{n}}", loading: "Consultando erupciones solares de NASA…", weather: "Última erupción clase {{cls}}", quiet: "Sol tranquilo — sin erupciones en 14 días", blocked: "NO-GO: corrige los puntos rojos en el constructor.", accept: "Acepto {{n}} punto(s) en ESPERA y asumo el riesgo", allgo: "Todas las estaciones GO. Autorizado para lanzar." },
  },
  concepts: {
    rocket: { title: "Ecuación del cohete y Δv", simple: "Un cohete expulsa combustible hacia atrás para avanzar. Un escape más rápido y más combustible dan un mayor cambio de velocidad, llamado delta-v (Δv).", demo: "Mira el escape: cada soplo de gas empuja el cohete en sentido contrario.", interactive: "Mueve los controles. Mira cómo la eficiencia del motor (Isp) y la relación de masas cambian el Δv.", isp: "Eficiencia del motor (Isp)", ratio: "Masa llena ÷ vacía", science: "Konstantín Tsiolkovski demostró que el Δv depende solo de la velocidad de escape y de la relación de masas. Por el logaritmo, añadir combustible ayuda cada vez menos.", formulaNote: "Isp = impulso específico (s), g₀ = 9,80665 m/s², m₀ = masa llena, m_f = masa vacía.", q: "¿Qué da más Δv a un cohete?", a: ["Duplicar el combustible", "Duplicar la velocidad de escape", "Siempre son iguales"], correct: 1, explain: "El Δv crece en proporción a la velocidad de escape, pero solo con el logaritmo de la relación de masas.", ayesha: "Toda misión empieza con una pregunta: ¿tenemos suficiente delta-v? Descubrámoslo juntos." },
    orbit: { title: "Órbitas y tiempo de viaje", simple: "Los planetas más lejanos del Sol se mueven más despacio y tardan más en dar la vuelta. Eso fija cuánto duran los viajes.", demo: "Los planetas interiores corren; los exteriores avanzan lentos.", interactive: "Arrastra la distancia. Mira cuánto dura una órbita.", dist: "Distancia al Sol (UA)", science: "Johannes Kepler descubrió que el cuadrado del periodo orbital es igual al cubo de la distancia, medidos en años y unidades astronómicas.", formulaNote: "T = periodo en años terrestres, a = distancia media en UA.", q: "Marte está a unas 1,52 UA del Sol. ¿Cuánto dura su año?", a: ["Cerca de 1 año terrestre", "Cerca de 1,9 años terrestres", "Cerca de 5 años terrestres"], correct: 1, explain: "1,52³ ≈ 3,5 y √3,5 ≈ 1,88 años — coincide con los 687 días de la NASA.", ayesha: "El momento lo es todo. Los planetas se mueven mientras viajamos, así que apuntamos a donde estarán." },
    light: { title: "Luz solar y retraso de señal", simple: "Lejos del Sol, los paneles solares reciben mucha menos luz. Los mensajes de radio también tardan más en llegar a casa.", demo: "La luz solar se extiende como una esfera creciente, así que se debilita con la distancia.", interactive: "Elige un destino. Mira la energía solar y el retraso de radio.", body: "Destino", power: "Energía solar frente a la Tierra", delay: "Retraso de radio (ida)", science: "La luz se reparte sobre una esfera, así que su intensidad cae con el cuadrado de la distancia. La radio viaja a la velocidad de la luz, unos 299.792 km por segundo.", formulaNote: "P = potencia, d = distancia en UA, c = velocidad de la luz.", q: "En Júpiter (5,2 UA), ¿cuánta luz reciben los paneles comparado con la Tierra?", a: ["Cerca del 50%", "Cerca del 20%", "Cerca del 4%"], correct: 2, explain: "1 ÷ 5,2² ≈ 0,037, cerca del 4% — por eso Juno necesita paneles enormes.", ayesha: "Lejos del Sol, la energía y la paciencia se vuelven valiosas. Planifica ambas." },
  },
  ayeshaTips: { build: "Revisa tu delta-v antes que nada. Si es menor que lo que pide la ruta, añade combustible o un motor más eficiente.", launch: "El lanzamiento es lo más difícil. Casi todo el combustible se gasta en escapar de la gravedad terrestre." },
};

const ar: Tree = {
  ui: {
    flow: { start: "ابدأ المهمة", planet: "اختر عالماً", mission: "اختر مهمة", routePick: "اختر المسار", routePreview: "معاينة المسار", objectives: "أهداف المهمة", budget: "ميزانية المهمة", fuel: "خطة الوقود", power: "خطة الطاقة", comms: "الاتصالات", instruments: "الأجهزة العلمية", overview: "ملخص المهمة", craft: "اختر المركبة", build: "عدّل المركبة", next: "التالي", back: "رجوع", learn: "تعلّم السبب", continue: "متابعة", selected: "تم الاختيار", surface: "استكشاف السطح", orbit: "دراسة المدار", survey: "مسح من بعيد", limited: "محدود", balanced: "متوازن", expanded: "موسع", explorer: "المستكشف", surveyor: "المسّاح", guardian: "الحارس", review: "راجع الخيارات", confirmRoute: "تأكيد المسار", changeRoute: "غيّر المسار", design: "صمّم المركبة", score: "درجة الهندسة", launchRisk: "الإطلاق رغم المخاطر", nasa: "مصدر ناسا", gameEstimate: "تقدير اللعبة", flight: "منظر الرحلة", control: "مركز التحكم", cockpit: "قمرة القيادة" },
    game: { home: "الرئيسية", missions: "المهام", brief: "إحاطة المهمة", route: "المسار", hangar: "الحظيرة", launch: "فحص الإطلاق", options: "الخيارات", graphics: "الرسومات", choose: "اختر وجهتك", chooseHint: "اختر عالمًا لاستكشافه.", destination: "الوجهة", gravity: "الجاذبية", year: "السنة", distance: "البعد عن الشمس", explore: "استكشف المهمة", plot: "خطط المسار", dragMap: "اسحب لاستكشاف المدار", flightPlan: "خطة الرحلة", transit: "العبور", required: "المطلوب", routeHint: "قارن المسارات باستخدام مدارات NASA/JPL.", toHangar: "إلى الحظيرة", assemble: "ابن مركبتك", dragCraft: "اسحب لتدوير المركبة", engine: "المحرك", fuel: "الوقود", power: "الطاقة", comms: "الاتصالات", science: "العلوم", engineCount: "المحركات", tanks: "خزانات الوقود", fuelLoad: "كمية الوقود", solar: "الأجنحة الشمسية", rtg: "وحدات RTG", battery: "البطارية", antennas: "الهوائيات", shield: "درع الحطام", installed: "الأجهزة المثبتة", mass: "كتلة الإطلاق", readiness: "الجاهزية", toCheck: "افحص الإطلاق" },
    nav: { home: "الرئيسية", missions: "المهام", learn: "تعلّم", archive: "الأرشيف" },
    home: { eyebrow: "كن", title1: "قائد", title2: "المهمة", sub: "صمّم المهمة. قُد الرحلة. تعلّم من كل قرار.", continue: "متابعة المهمة", current: "المهمة الحالية", notStarted: "لم تبدأ", attempt: "المحاولة {{n}} · جارية", newMission: "مهمة جديدة", archive: "أرشيف المهام", tagline: "قرارات صغيرة. رحلات كبيرة." },
    learn: { title: "مختبر العلوم", mentorTitle: "مرشدة العلوم للمهمة", mentorGreeting: "مرحبًا بك في مختبر العلوم أيها القائد! تعلّم فيزياء الفضاء الأساسية قبل بدء رحلتك.", pick: "اختر مفهومًا. يستغرق كل واحد نحو دقيقتين.", close: "إغلاق", back: "كل المفاهيم", next: "الخطوة التالية", prev: "السابق", step: "الخطوة {{n}} من 7", check: "تحقق من الإجابة", correct: "صحيح!", wrong: "ليس تمامًا — حاول مجددًا.", source: "المصدر", result: "النتيجة" },
    steps: ["فكرة بسيطة", "شاهد", "جرّب الأرقام", "العلم الحقيقي", "المعادلة", "جرّبها", "مصدر المعلومة"],
    voice: { play: "تشغيل", pause: "إيقاف مؤقت", resume: "استئناف", replay: "إعادة", mute: "كتم", unmute: "إلغاء الكتم", captionsOn: "الترجمة مفعّلة", captionsOff: "الترجمة متوقفة", language: "اللغة", unsupported: "الصوت غير متاح على هذا الجهاز. تُعرض الترجمة بدلًا منه.", noVoice: "لا يوجد صوت مثبت لهذه اللغة على هذا الجهاز. تُعرض الترجمة بدلًا منه.", speaking: "تتحدث", paused: "متوقف" },
    ayesha: { name: "د. عائشة", role: "عالمة المهمة", dismiss: "فهمت", listen: "استمع" },
    brief: { kicker: "إحاطة المهمة", objective: "الهدف", target: "حقائق الوجهة", diameter: "القطر", distance: "المسافة من الشمس", period: "الفترة المدارية", gravity: "جاذبية السطح", signal: "تأخر الإشارة إلى الأرض (متوسط)", dv: "Δv المطلوبة من مدار الأرض", duration: "زمن العبور (هوهمان)", why: "لماذا يهم", image: "صورة ناسا للوجهة", loading: "جارٍ تحميل صورة ناسا…", none: "لا توجد صورة من ناسا", back: "العودة إلى المهام", plan: "خطط المسار", source: "المصادر" },
    live: { title: "المواقع الحقيقية اليوم", loading: "جارٍ سؤال NASA/JPL Horizons…", distance: "الأرض ← {{body}} الآن", delay: "تأخر الراديو باتجاه واحد", srcLive: "المصدر: تقويم NASA/JPL Horizons (اليوم)", srcDemo: "تعذر الوصول إلى Horizons — عناصر مدارية متوسطة من NASA/JPL" },
    dv: { title: "معادلة الصاروخ — مركبتك", have: "لديك", need: "يحتاج المسار", ok: "آمن: هامش {{pct}}% فوق الحاجة.", warn: "ضيق: هامش {{pct}}% فقط. قد يعلقك أي انحراف.", bad: "غير كافٍ: ينقص {{pct}}%. لا تستطيع المركبة الوصول.", fixTanks: "أضف خزانات وقود أو املأها أكثر", fixEngine: "اختر محركًا أكفأ (Isp أعلى)", fixMass: "أزل القطع الثقيلة غير الضرورية", src: "بيانات المحرك" },
    poll: { title: "استطلاع مدير الرحلة GO / NO-GO", name: { booster: "الصاروخ", prop: "الدفع", power: "الطاقة", comms: "الاتصالات", shield: "الدرع", science: "العلوم", weather: "طقس الفضاء" }, go: "GO", hold: "انتظار", nogo: "NO-GO", booster: "{{pct}}% من حد SLS", prop: "هامش Δv {{pct}}%", power: "{{gen}} ك.و منتجة، {{draw}} ك.و مستهلكة", comms: "{{n}} هوائي", shield: "خطر المسار {{pct}}%", science: "القيمة العلمية {{n}}", loading: "جارٍ فحص التوهجات الشمسية من NASA…", weather: "آخر توهج من الفئة {{cls}}", quiet: "الشمس هادئة — لا توهجات منذ 14 يومًا", blocked: "NO-GO: أصلح البنود الحمراء في المُنشئ قبل الإطلاق.", accept: "أقبل {{n}} بند انتظار وأتحمل المخاطرة", allgo: "جميع المحطات GO. مسموح بالإطلاق." },
  },
  concepts: {
    rocket: { title: "معادلة الصاروخ وΔv", simple: "يدفع الصاروخ الوقود إلى الخلف ليتحرك إلى الأمام. العادم الأسرع والوقود الأكثر يعطيان تغيرًا أكبر في السرعة يسمى دلتا-في (Δv).", demo: "راقب العادم: كل دفعة غاز تدفع الصاروخ في الاتجاه المعاكس.", interactive: "حرّك المنزلقات. شاهد كيف تغيّر كفاءة المحرك (Isp) ونسبة الكتلة قيمة Δv.", isp: "كفاءة المحرك (Isp)", ratio: "الكتلة الممتلئة ÷ الفارغة", science: "أثبت كونستانتين تسيولكوفسكي أن Δv يعتمد فقط على سرعة العادم ونسبة الكتلة. وبسبب اللوغاريتم، تقل فائدة إضافة الوقود تدريجيًا.", formulaNote: "Isp = الدفع النوعي (ثانية)، g₀ = 9.80665 م/ث²، m₀ = الكتلة الممتلئة، m_f = الكتلة الفارغة.", q: "ما الذي يعطي الصاروخ Δv أكبر؟", a: ["مضاعفة الوقود", "مضاعفة سرعة العادم", "هما متساويان دائمًا"], correct: 1, explain: "يزداد Δv بالتناسب مع سرعة العادم، لكن فقط مع لوغاريتم نسبة الكتلة.", ayesha: "كل مهمة تبدأ بسؤال واحد: هل لدينا ما يكفي من دلتا-في؟ لنكتشف ذلك معًا." },
    orbit: { title: "المدارات وزمن الرحلة", simple: "الكواكب الأبعد عن الشمس تتحرك أبطأ وتستغرق وقتًا أطول لتدور حولها. وهذا يحدد مدة الرحلات.", demo: "الكواكب الداخلية تسرع؛ والخارجية تزحف.", interactive: "اسحب المسافة. شاهد كم تستغرق دورة واحدة.", dist: "المسافة عن الشمس (وحدة فلكية)", science: "اكتشف يوهانس كبلر أن مربع زمن الدورة يساوي مكعب المسافة عند قياسهما بالسنوات والوحدات الفلكية.", formulaNote: "T = زمن الدورة بسنوات الأرض، a = متوسط المسافة بالوحدة الفلكية.", q: "يبعد المريخ نحو 1.52 وحدة فلكية عن الشمس. كم تقريبًا طول سنته؟", a: ["نحو سنة أرضية واحدة", "نحو 1.9 سنة أرضية", "نحو 5 سنوات أرضية"], correct: 1, explain: "1.52³ ≈ 3.5 و√3.5 ≈ 1.88 سنة — يطابق 687 يومًا حسب ناسا.", ayesha: "التوقيت هو كل شيء. الكواكب تتحرك أثناء رحلتنا، لذا نصوّب نحو مكانها المستقبلي." },
    light: { title: "ضوء الشمس وتأخر الإشارة", simple: "بعيدًا عن الشمس تتلقى الألواح الشمسية ضوءًا أقل بكثير. وتستغرق رسائل الراديو وقتًا أطول للوصول إلى الأرض.", demo: "ينتشر ضوء الشمس ككرة تكبر، لذا يضعف مع المسافة.", interactive: "اختر وجهة. شاهد الطاقة الشمسية وتأخر الراديو.", body: "الوجهة", power: "الطاقة الشمسية مقارنة بالأرض", delay: "تأخر الراديو باتجاه واحد", science: "ينتشر الضوء على سطح كرة، فتنخفض شدته مع مربع المسافة. تنتقل إشارات الراديو بسرعة الضوء، نحو 299,792 كم في الثانية.", formulaNote: "P = الطاقة، d = المسافة بالوحدة الفلكية، c = سرعة الضوء.", q: "عند المشتري (5.2 وحدة فلكية)، كم ضوءًا تتلقى الألواح مقارنة بالأرض؟", a: ["نحو 50%", "نحو 20%", "نحو 4%"], correct: 2, explain: "1 ÷ 5.2² ≈ 0.037، أي نحو 4% — لهذا يحتاج جونو ألواحًا ضخمة.", ayesha: "بعيدًا عن الشمس تصبح الطاقة والصبر ثمينين. خطط لكليهما." },
  },
  ayeshaTips: { build: "تحقق من دلتا-في أولًا. إذا كانت أقل مما يحتاجه المسار، أضف وقودًا أو محركًا أكفأ.", launch: "الإطلاق هو أصعب جزء. يُستهلك معظم الوقود للإفلات من جاذبية الأرض فقط." },
};

const fr: Tree = {
  ui: {
    flow: { start: "Lancer la mission", planet: "Choisir un monde", mission: "Choisir une mission", routePick: "Choisir un trajet", routePreview: "Voir le trajet", objectives: "Objectifs", budget: "Budget mission", fuel: "Plan carburant", power: "Plan énergie", comms: "Communications", instruments: "Instruments scientifiques", overview: "Vue de la mission", craft: "Choisir un vaisseau", build: "Modifier le vaisseau", next: "Suivant", back: "Retour", learn: "Comprendre pourquoi", continue: "Continuer", selected: "Sélectionné", surface: "Explorer la surface", orbit: "Étudier l’orbite", survey: "Observer de loin", limited: "Limité", balanced: "Équilibré", expanded: "Étendu", explorer: "Explorateur", surveyor: "Observateur", guardian: "Gardien", review: "Vérifier les choix", confirmRoute: "Confirmer le trajet", changeRoute: "Changer de trajet", design: "Concevoir le vaisseau", score: "Score technique", launchRisk: "Lancer avec risque", nasa: "Source NASA", gameEstimate: "Estimation du jeu", flight: "Vue en vol", control: "Centre de contrôle", cockpit: "Cockpit" },
    game: { home: "Accueil", missions: "Missions", brief: "Briefing", route: "Trajet", hangar: "Hangar", launch: "Vérification", options: "Options", graphics: "Graphismes", choose: "Choisis ta destination", chooseHint: "Choisis un monde à explorer.", destination: "Destination", gravity: "Gravité", year: "Année", distance: "Distance du Soleil", explore: "Explorer la mission", plot: "Trace la route", dragMap: "Glisse pour voir les orbites", flightPlan: "Plan de vol", transit: "Transit", required: "Requis", routeHint: "Compare les trajets avec les orbites NASA/JPL.", toHangar: "Aller au hangar", assemble: "Construis ton vaisseau", dragCraft: "Glisse pour tourner le vaisseau", engine: "Moteur", fuel: "Carburant", power: "Énergie", comms: "Communications", science: "Science", engineCount: "Moteurs", tanks: "Réservoirs", fuelLoad: "Charge de carburant", solar: "Panneaux solaires", rtg: "Unités RTG", battery: "Batterie", antennas: "Antennes", shield: "Bouclier anti-débris", installed: "Instruments installés", mass: "Masse au lancement", readiness: "Préparation", toCheck: "Vérifier le lancement" },
    nav: { home: "Accueil", missions: "Missions", learn: "Apprendre", archive: "Archives" },
    home: { eyebrow: "DEVENEZ", title1: "Commandant", title2: "de mission", sub: "Concevez la mission. Pilotez le voyage. Apprenez de chaque décision.", continue: "Continuer la mission", current: "MISSION EN COURS", notStarted: "Pas commencée", attempt: "Tentative {{n}} · En cours", newMission: "Nouvelle mission", archive: "Archives des missions", tagline: "PETITES DÉCISIONS. GRANDS VOYAGES." },
    learn: { title: "Labo des sciences", mentorTitle: "Mentore scientifique de mission", mentorGreeting: "Bienvenue au Labo des sciences, commandant ! Maîtrisez la physique spatiale fondamentale avant votre voyage.", pick: "Choisissez un concept. Chacun prend environ deux minutes.", close: "Fermer", back: "Tous les concepts", next: "Étape suivante", prev: "Précédent", step: "Étape {{n}} sur 7", check: "Vérifier", correct: "Correct !", wrong: "Pas tout à fait — réessayez.", source: "Source", result: "Résultat" },
    steps: ["Idée simple", "Observez", "Testez les chiffres", "Vraie science", "Formule", "À vous", "D'où ça vient"],
    voice: { play: "Lire", pause: "Pause", resume: "Reprendre", replay: "Rejouer", mute: "Couper le son", unmute: "Activer le son", captionsOn: "Sous-titres activés", captionsOff: "Sous-titres désactivés", language: "Langue", unsupported: "La voix n'est pas disponible sur cet appareil. Les sous-titres sont affichés.", noVoice: "Aucune voix installée pour cette langue sur cet appareil. Les sous-titres sont affichés.", speaking: "Parle", paused: "En pause" },
    ayesha: { name: "Dr Ayesha", role: "Scientifique de mission", dismiss: "Compris", listen: "Écouter" },
    brief: { kicker: "BRIEFING DE MISSION", objective: "Objectif", target: "Données de la cible", diameter: "Diamètre", distance: "Distance au Soleil", period: "Période orbitale", gravity: "Gravité de surface", signal: "Délai du signal vers la Terre (moyen)", dv: "Δv nécessaire depuis l'orbite terrestre", duration: "Temps de transit (Hohmann)", why: "Pourquoi c'est important", image: "Image NASA de la cible", loading: "Chargement de l'image NASA…", none: "Aucune image NASA disponible", back: "Retour aux missions", plan: "Planifier la route", source: "Sources" },
    live: { title: "POSITIONS RÉELLES DU JOUR", loading: "Interrogation de NASA/JPL Horizons…", distance: "Terre → {{body}} maintenant", delay: "Délai radio aller simple", srcLive: "Source : éphémérides NASA/JPL Horizons (aujourd'hui)", srcDemo: "Horizons injoignable — éléments orbitaux moyens NASA/JPL" },
    dv: { title: "ÉQUATION DE LA FUSÉE — TON VAISSEAU", have: "Tu as", need: "La route exige", ok: "Sûr : {{pct}} % de marge au-dessus du besoin.", warn: "Serré : seulement {{pct}} % de marge. Un détour pourrait te bloquer.", bad: "Insuffisant : il manque {{pct}} %. Ce vaisseau ne peut pas atteindre la cible.", fixTanks: "Ajoute des réservoirs ou remplis-les davantage", fixEngine: "Choisis un moteur plus efficace (Isp plus élevé)", fixMass: "Retire les pièces lourdes inutiles", src: "Données moteur" },
    poll: { title: "SONDAGE GO / NO-GO DU DIRECTEUR DE VOL", name: { booster: "Lanceur", prop: "Propulsion", power: "Énergie", comms: "Communications", shield: "Blindage", science: "Science", weather: "Météo spatiale" }, go: "GO", hold: "ATTENTE", nogo: "NO-GO", booster: "{{pct}} % de la limite du SLS", prop: "Marge Δv {{pct}} %", power: "{{gen}} kW produits, {{draw}} kW consommés", comms: "{{n}} antenne(s)", shield: "Risque de route {{pct}} %", science: "Valeur scientifique {{n}}", loading: "Vérification des éruptions solaires NASA…", weather: "Dernière éruption classe {{cls}}", quiet: "Soleil calme — aucune éruption en 14 jours", blocked: "NO-GO : corrige les points rouges dans le constructeur.", accept: "J’accepte {{n}} point(s) en ATTENTE et le risque", allgo: "Toutes les stations GO. Autorisé au lancement." },
  },
  concepts: {
    rocket: { title: "Équation de la fusée et Δv", simple: "Une fusée éjecte du carburant vers l'arrière pour avancer. Un échappement plus rapide et plus de carburant donnent un plus grand changement de vitesse, appelé delta-v (Δv).", demo: "Regardez l'échappement : chaque bouffée de gaz pousse la fusée dans l'autre sens.", interactive: "Bougez les curseurs. Voyez comment l'efficacité du moteur (Isp) et le rapport de masse changent le Δv.", isp: "Efficacité du moteur (Isp)", ratio: "Masse pleine ÷ vide", science: "Konstantin Tsiolkovski a montré que le Δv dépend seulement de la vitesse d'éjection et du rapport de masse. À cause du logarithme, ajouter du carburant aide de moins en moins.", formulaNote: "Isp = impulsion spécifique (s), g₀ = 9,80665 m/s², m₀ = masse pleine, m_f = masse vide.", q: "Qu'est-ce qui donne le plus de Δv à une fusée ?", a: ["Doubler le carburant", "Doubler la vitesse d'éjection", "C'est toujours pareil"], correct: 1, explain: "Le Δv croît proportionnellement à la vitesse d'éjection, mais seulement avec le logarithme du rapport de masse.", ayesha: "Chaque mission commence par une question : avons-nous assez de delta-v ? Découvrons-le ensemble." },
    orbit: { title: "Orbites et durée du voyage", simple: "Les planètes plus éloignées du Soleil vont plus lentement et mettent plus de temps à en faire le tour. Cela fixe la durée des voyages.", demo: "Les planètes intérieures filent ; les extérieures rampent.", interactive: "Faites glisser la distance. Voyez la durée d'une orbite.", dist: "Distance au Soleil (UA)", science: "Johannes Kepler a découvert que le carré de la période orbitale égale le cube de la distance, mesurés en années et en unités astronomiques.", formulaNote: "T = période en années terrestres, a = distance moyenne en UA.", q: "Mars est à environ 1,52 UA du Soleil. Combien dure son année ?", a: ["Environ 1 année terrestre", "Environ 1,9 année terrestre", "Environ 5 années terrestres"], correct: 1, explain: "1,52³ ≈ 3,5 et √3,5 ≈ 1,88 an — cela correspond aux 687 jours de la NASA.", ayesha: "Tout est question de timing. Les planètes bougent pendant le voyage, alors on vise là où elles seront." },
    light: { title: "Lumière solaire et délai du signal", simple: "Loin du Soleil, les panneaux solaires reçoivent beaucoup moins de lumière. Les messages radio mettent aussi plus de temps à revenir.", demo: "La lumière se répand comme une sphère qui grandit, elle faiblit donc avec la distance.", interactive: "Choisissez une destination. Voyez l'énergie solaire et le délai radio.", body: "Destination", power: "Énergie solaire vs Terre", delay: "Délai radio aller simple", science: "La lumière se répartit sur une sphère, donc son intensité baisse avec le carré de la distance. La radio voyage à la vitesse de la lumière, environ 299 792 km par seconde.", formulaNote: "P = puissance, d = distance en UA, c = vitesse de la lumière.", q: "À Jupiter (5,2 UA), combien de lumière les panneaux reçoivent-ils par rapport à la Terre ?", a: ["Environ 50 %", "Environ 20 %", "Environ 4 %"], correct: 2, explain: "1 ÷ 5,2² ≈ 0,037, soit environ 4 % — c'est pourquoi Juno a d'immenses panneaux.", ayesha: "Loin du Soleil, l'énergie et la patience deviennent précieuses. Prévoyez les deux." },
  },
  ayeshaTips: { build: "Vérifiez votre delta-v avant tout. S'il est inférieur au besoin de la route, ajoutez du carburant ou un moteur plus efficace.", launch: "Le lancement est la partie la plus dure. La plupart du carburant sert juste à échapper à la gravité terrestre." },
};

export const resources = { en: { translation: en }, bn: { translation: bn }, hi: { translation: hi }, es: { translation: es }, ar: { translation: ar }, fr: { translation: fr } };
export const LANGS = [
  { id: "en", label: "English", speech: "en-US" }, { id: "bn", label: "বাংলা", speech: "bn-BD" }, { id: "hi", label: "हिन्दी", speech: "hi-IN" },
  { id: "es", label: "Español", speech: "es-ES" }, { id: "ar", label: "العربية", speech: "ar-SA", rtl: true }, { id: "fr", label: "Français", speech: "fr-FR" },
] as const;
